# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  generate:
    desc: Generate assets
    cmds:
      - go generate ./...
  run:
    deps: [generate]
    desc: Run the program in development mode
    cmds:
      - go run ./cmd/videosite
    aliases: [default]
  db:
    desc: SQLite REPL
    cmds:
      - sqlite3 ./var/data.db

  docker:
    desc: Build and push both Docker images
    deps:
      - "docker:www"
      - "docker:encoder"

  docker:www:
    desc: Build and push the www Docker image
    vars:
      TAG: '{{.TAG | default "latest"}}'
      REGISTRY: '{{.REGISTRY | default "ghcr.io/tigrisdata-community/videosite"}}'
    cmds:
      - docker build -f docker/www.Dockerfile --platform linux/amd64 -t {{.REGISTRY}}/www:{{.TAG}} .
      - docker push {{.REGISTRY}}/www:{{.TAG}}

  docker:encoder:
    desc: Build and push the encoder Docker image
    vars:
      TAG: '{{.TAG | default "latest"}}'
      REGISTRY: '{{.REGISTRY | default "ghcr.io/tigrisdata-community/videosite"}}'
    cmds:
      - docker build -f docker/encoder.Dockerfile --platform linux/amd64 -t {{.REGISTRY}}/encoder:{{.TAG}} .
      - docker push {{.REGISTRY}}/encoder:{{.TAG}}
